# Generated by Django 2.2.20 on 2021-05-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(blank=True, max_length=512, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('language_code', models.CharField(blank=True, max_length=8, null=True)),
                ('registered_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
